const fs = require('fs');
let content = fs.readFileSync('src/lib/audio.ts', 'utf8');
content = content.replace(`    rolloff: number;
    lowEnergyPct: number;
    midEnergyPct: number;
    highEnergyPct: number;
    eqOffsets: Float32Array;
    midEqOffsets: Float32Array;
    sideEqOffsets: Float32Array;
    dynEqAmount: Float32Array;
    rolloff: number;
    lowEnergyPct: number;
    midEnergyPct: number;
    highEnergyPct: number;`, `    eqOffsets: Float32Array;
    midEqOffsets: Float32Array;
    sideEqOffsets: Float32Array;
    dynEqAmount: Float32Array;
    rolloff: number;
    lowEnergyPct: number;
    midEnergyPct: number;
    highEnergyPct: number;`);
fs.writeFileSync('src/lib/audio.ts', content);
